# Numpy in Python

In [1]:
import numpy as np

x = np.array([1,2,3,4])
print(x)

print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [2]:
y = [4,8,7]
print(y)

print(type(y))

[4, 8, 7]
<class 'list'>


# Speed 

***List***

In [3]:
%timeit [j**4 for j in range(1,9)]

661 ns ± 13.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


***Array***

In [4]:
import numpy as np

%timeit np.arange(1,9)**4

4.89 µs ± 565 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Array

In [5]:
import numpy as np

x = [1,2,3,4]

y = np.array(x)

print(y)

[1 2 3 4]


In [6]:
import numpy as np

y = np.array([1,2,3,4,5])

print(y)
print(type(y))
print(y.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [7]:
l = []

for i in range(1,5):
    int_1 = input("enter :")
    l.append(int_1)
    
print(np.array(l))

enter :1
enter :2
enter :2
enter :3
['1' '2' '2' '3']


In [8]:
D2 = np.array([[1,2,3],[4,5,6]])
print(D2)
print(D2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [9]:
D3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(D3)
print(D3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [10]:
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)

print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Zeros

In [11]:
import numpy as np

ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))

print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones

In [12]:
import numpy as np

ar_one = np.ones(4)
ar_one1 = np.ones((5,5))

print(ar_one)
print()
print(ar_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Empty

In [13]:
ar_em = np.empty(4)

print(ar_em)

[1. 1. 1. 1.]


# Range

In [14]:
ar_rn = np.arange(4)

print(ar_rn)

[0 1 2 3]


# Diagonal

In [15]:
ar_dia = np.eye(3)

print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
ar_dia = np.eye(3,3)

print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# linspace

In [17]:
ar_lin = np.linspace(1,10,num = 5)

print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]


In [18]:
ar_lin = np.linspace(0,10,num = 5)

print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


# Random Numbers

1. rand()
2. randn()
3. ranf()
4. randint()

***1. rand()***

In [19]:
import numpy as np #all number b/w 0&1

var = np.random.rand(4)

print(var)

[0.58801397 0.10965773 0.28381576 0.64194669]


In [20]:
var = np.random.rand(2,5)

print(var)

[[0.45901869 0.0692161  0.44115707 0.01644511 0.58622091]
 [0.40349668 0.49177967 0.58419787 0.5763101  0.8831752 ]]


***2. randn()***

In [21]:
import numpy as np # +,- all numbers are allow

var = np.random.randn(4)

print(var)

[ 0.04794806  0.67953149 -0.73776621 -1.58085503]


In [22]:
var = np.random.randn(2,5)

print(var)

[[-0.2218276  -1.15534446 -0.09190857  2.43975921 -0.84125445]
 [-0.33963403  0.79739767 -1.68633288  0.33741604 -1.97540283]]


***3. ranf()***

In [23]:
import numpy as np # give the value between 0.0 & 1.0

var = np.random.ranf(4)

print(var)

[0.9384029  0.81494771 0.55578847 0.65545669]


***4. randint()***

In [24]:
import numpy as np 

#var = np.random.randint(min,max,total_values)

var = np.random.randint(5,20,5)

print(var)

[ 8 18 12 13 19]


# Data Type in NumPy Array

***1. int()***

In [25]:
import numpy as np

var = np.array([1,2,3,4])

print("Data Type : ",var.dtype )

Data Type :  int32


***2. float()***

In [26]:
import numpy as np

var = np.array([1.2,2.0,3.5,4.8])

print("Data Type : ",var.dtype )

Data Type :  float64


***3. string()***

In [27]:
var = np.array(["chanda","gudiya","yashu"])

print("Data Type : ",var.dtype)

Data Type :  <U6


In [28]:
var = np.array(["C","H","A",1,2,3])

print(var)

print("Data Type : ",var.dtype)

['C' 'H' 'A' '1' '2' '3']
Data Type :  <U11


In [29]:
x = np.array([1,2,3,4],dtype = np.int8)

print("Data Type : ",x.dtype)
print()
print(x)

Data Type :  int8

[1 2 3 4]


In [30]:
x = np.array([1,2,3,4],dtype = "f")

print("Data Type : ",x.dtype)
print()
print(x)

Data Type :  float32

[1. 2. 3. 4.]


In [31]:
x = np.array([1,2,3,4])

new = np.float32(x)

print("Data Type : ",x.dtype)
print("Data Type : ",new.dtype)
print()
print(x)
print(new)

Data Type :  int32
Data Type :  float32

[1 2 3 4]
[1. 2. 3. 4.]


# Arithmetic Operation

1. add()
2. subtract()
3. multiply()
4. divide()
5. mod()
6. power()
7. reciprocal()

***1. add()***

In [32]:
import numpy as np

var = np.array([1,2,3,4])

varadd = var + 3

print(varadd)

[4 5 6 7]


In [33]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1 + var2

print(varadd)

[2 4 6 8]


In [34]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = np.add(var1,var2)

print(varadd)

[2 4 6 8]


***2. subtract()***

In [35]:
import numpy as np

var = np.array([1,2,3,4])

varadd = var - 3

print(varadd)

[-2 -1  0  1]


***3. multiply()***

In [36]:
import numpy as np

var = np.array([1,2,3,4])

varadd = var * 3

print(varadd)

[ 3  6  9 12]


***4. mod()***

In [37]:
import numpy as np

var = np.array([1,2,3,4])

varadd = var % 3

print(varadd)

[1 2 0 1]


***5. divide()***

In [38]:
import numpy as np

var = np.array([1,2,3,4])

varadd = var / 3

print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


***6. power()***

In [39]:
import numpy as np

var = np.array([1,2,3,4])

varadd = var ** 3

print(varadd)

[ 1  8 27 64]


***7. reciprocal()***

In [40]:
import numpy as np

var1 = np.array([5,6,7,8])
var2 = np.array([1,2,3,4])

x = np.array([var1 , var2])

array_rec = np.reciprocal(x)

print(array_rec)

[[0 0 0 0]
 [1 0 0 0]]


In [41]:
import numpy as np

var = np.array([1,2,3,4])

varadd = np.reciprocal(var)

print(varadd)

[1 0 0 0]


# 2D Array

In [42]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()

varadd = var21 + var22

print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [43]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()

varadd = var21 * var22

print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[ 1  4  9 16]
 [ 1  4  9 16]]


In [44]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()

varadd = var21 - var22

print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[0 0 0 0]
 [0 0 0 0]]


# Arithmetic Functions

1. min()
2. max()
3. argmin()
4. sqrt()
5. sin()
6. cos()
7. cumsum()

In [45]:
import numpy as np

var = np.array([1,2,3,4,5,3,2])

print("min : ",np.min(var),np.argmin(var))    #arg means index numbers perticular number ki
print("max : ",np.max(var),np.argmax(var))
print("sqrt : ",np.sqrt(var))

min :  1 0
max :  5 4
sqrt :  [1.         1.41421356 1.73205081 2.         2.23606798 1.73205081
 1.41421356]


In [46]:
var1 = np.array([[2,1,4],[9,8,5]])

print(np.min(var1,axis=1))  #compare sprate index
print(np.min(var1,axis=0))  #compare between 0 and 1 index

[1 5]
[2 1 4]


In [47]:
var2 = np.array([1,2,3])

print(np.sin(var2))
print(np.cos(var2))
print(np.cumsum(var2)) # add number for previous value

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]


# Shape and Reshape Array

***Shape***

In [48]:
import numpy as np

var = np.array([[1,2,5],[1,2,3]])

print(var)
print()
print(var.shape)

[[1 2 5]
 [1 2 3]]

(2, 3)


In [49]:
var1 = np.array([1,2,3,4], ndmin = 4)

print(var1)
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


***Reshape***

In [50]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)

print()

x = var2.reshape(3,2)

print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [51]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)

print()

x1 = var3.reshape(2,3,2)

print(x)
print(x.ndim)

one = x1.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[1 2]
 [3 4]
 [5 6]]
2
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


# Broadcasting in NumPy

In [52]:
import numpy as np

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

print(var1 + var2)

[2 4 6 8]


In [53]:
import numpy as np

var1 = np.array([1,2,3])
print(var1.shape)
print()
print(var1)
print()

var2 = np.array([[1],[2],[3]])
print(var2.shape)
print()
print(var2)
print()
print(var1 + var2)

(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [54]:
x = np.array([[1],[2]])
print(x.shape)
print()
y = np.array([[1,2,3],[1,2,3]])
print(y.shape)
print()
print(x+y)

(2, 1)

(2, 3)

[[2 3 4]
 [3 4 5]]


# Indexing and Slicing in NumPy Arrays

***Indexing***

In [55]:
import numpy as np

var = np.array([9,8,7,6])

print(var[1])
print(var[-3])

8
8


In [56]:
var1 = np.array([[9,8,7],[4,5,6]])

print(var1)
print(var1.ndim)
print()

print(var1[0,2])

[[9 8 7]
 [4 5 6]]
2

7


In [57]:
var2 = np.array([[[1,2],[1,2]]])

print(var2)
print(var2.ndim)
print()
print(var2[0,1])

[[[1 2]
  [1 2]]]
3

[1 2]


***Slicing***

In [58]:
import numpy as np

var = np.array([1,2,3,4,5,6,7])

print(var)
print()
print("2 to 5 : ",var[1:5])

print("2 to End : ",var[1:])

print("start to 5 : ",var[:5])

print("stop : ",var[::2])

print("stop : ",var[1:5:2]) #start:stop:step

[1 2 3 4 5 6 7]

2 to 5 :  [2 3 4 5]
2 to End :  [2 3 4 5 6 7]
start to 5 :  [1 2 3 4 5]
stop :  [1 3 5 7]
stop :  [2 4]


In [59]:
var1 = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])

print(var1)
print()

print("8 to 5 : ",var1[2,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

8 to 5 :  [12 13 14 15]


# Iteration NumPy Array

In [60]:
import numpy as np

var = np.array([1,3,5,7,9,8,6,4,2])
print(var)
print()

for i in var :
    print(i)

[1 3 5 7 9 8 6 4 2]

1
3
5
7
9
8
6
4
2


In [61]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()

for j in var1 :
    print(j)
print()

for k in var1 :
    for l in k :
        print(l)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [62]:
var3 = np.array([[[1,2,3,4],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()

for i in var3 :
    for j in i : 
        for k in j :
            print(k)

[[[1 2 3 4]
  [1 2 3 4]]]
3

1
2
3
4
1
2
3
4


In [63]:
var3 = np.array([[[1,2,3,4],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()

for i in np.nditer(var3):
            print(i)

[[[1 2 3 4]
  [1 2 3 4]]]
3

1
2
3
4
1
2
3
4


In [64]:
var3 = np.array([[[1,2,3,4],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()

for i,d in np.ndenumerate(var3):
            print(i,d)

[[[1 2 3 4]
  [1 2 3 4]]]
3

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


# Copy and View in NumPy Arrays

In [65]:
import numpy as np

var = np.array([1,2,3,4])

co = var.copy()
var[1] = 60
print("var : ",var)
print("copy : ",co)

var :  [ 1 60  3  4]
copy :  [1 2 3 4]


In [66]:
x = np.array([9,8,7,6,5])

vi = x.view()
x[1] = 80
print("x : ",x)
print("view : ",vi)

x :  [ 9 80  7  6  5]
view :  [ 9 80  7  6  5]


# Join & Split Functions

***join Array***

In [67]:
import numpy as np

var = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])

ar = np.concatenate((var,var1))

print(ar)

[1 2 3 4 9 8 7 6]


In [68]:
import numpy as np

vr = np.array([[1,2],[3,4]])
vr1 = np.array([[9,8],[7,6]])

ar_new = np.concatenate((vr,vr1),axis = 1)

print(vr)
print()
print(vr1)
print()
print(ar_new)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2 9 8]
 [3 4 7 6]]


In [69]:
import numpy as np

var_1 = np.array([1,2,3,4])
var_2 = np.array([9,8,7,6])

a_new = np.stack((var_1,var_2),axis = 1)

print(a_new)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]


In [70]:
import numpy as np

var_1 = np.array([1,2,3,4])
var_2 = np.array([9,8,7,6])

a_new = np.stack((var_1,var_2),axis = 0)

print(a_new)

[[1 2 3 4]
 [9 8 7 6]]


In [71]:
import numpy as np

var_1 = np.array([1,2,3,4])
var_2 = np.array([9,8,7,6])

a_new = np.hstack((var_1,var_2)) #row

print(a_new)

[1 2 3 4 9 8 7 6]


In [72]:
import numpy as np

var_1 = np.array([1,2,3,4])
var_2 = np.array([9,8,7,6])

a_new = np.vstack((var_1,var_2)) #column

print(a_new)

[[1 2 3 4]
 [9 8 7 6]]


In [73]:
import numpy as np

var_1 = np.array([1,2,3,4])
var_2 = np.array([9,8,7,6])

a_new = np.dstack((var_1,var_2)) #height

print(a_new)

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


***Split Array***

In [74]:
import numpy as np

var = np.array([1,2,3,4,5,6])

print(var)

ar = np.array_split(var,2)

print()
print(ar)
print(type(ar))
print(ar[1])

[1 2 3 4 5 6]

[array([1, 2, 3]), array([4, 5, 6])]
<class 'list'>
[4 5 6]


In [75]:
var1 = np.array([[1,2],[3,4],[5,6]])

print(var1)

ar1 = np.array_split(var1,3)

print()
print(ar1)

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


In [76]:
var1 = np.array([[1,2],[3,4],[5,6]])

print(var1)

ar1 = np.array_split(var1,3)
ar2 = np.array_split(var1,3,axis=1)

print()
print(ar1)
print()
print(ar2)

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]


# Array Functions

1. Search
2. Sort
3. Filter
4. Shuffle
5. Unique
6. Resize
7. Flatten
8. Ravel
9. Insert
10. Append
11. Delete

***1. Search***

In [77]:
import numpy as np

var = np.array([1,2,3,4,5,6,4,3])

x = np.where((var%2) == 0)
y = np.where(var == 4)

print(x)
print(y)

(array([1, 3, 5, 6], dtype=int64),)
(array([3, 6], dtype=int64),)


In [78]:
var1 = np.array([1,2,3,4,6,7,8,9])

x1 = np.searchsorted(var1 , [5,6,7] , side = "right")

print(x1)

[4 5 6]


***2. Sort***

In [79]:
var_2 = np.array([4,3,2,5,6,76,5,43,78,24,90])

print(np.sort(var_2))

[ 2  3  4  5  5  6 24 43 76 78 90]


In [80]:
var_2 = np.array(["a","s","d","f"])

print(np.sort(var_2))

['a' 'd' 'f' 's']


In [81]:
var_2 = np.array([[4,3,2,5,6,76,5],[43,78,24,90,8,7,88]])

print(np.sort(var_2))

[[ 2  3  4  5  5  6 76]
 [ 7  8 24 43 78 88 90]]


***3. Filter***

In [82]:
var_3 = np.array(["a","s","d","f"])

f = [True,False,False,True]

new_a = var_3[f]

print(new_a)
print(type(new_a))

['a' 'f']
<class 'numpy.ndarray'>


***4. Shuffle***

In [83]:
var = np.array([1,2,3,4,5])

np.random.shuffle(var)

print(var)

[5 4 1 3 2]


***5. Unique***

In [84]:
var1 = np.array([1,2,3,4,5,3,4,6,7,8,9,2,1])

x = np.unique(var1)
y = np.unique(var1,return_index = True)
z = np.unique(var1,return_index = True,return_counts=True)

print(x)
print()
print(y)
print()
print(z)

[1 2 3 4 5 6 7 8 9]

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 0,  1,  2,  3,  4,  7,  8,  9, 10], dtype=int64))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 0,  1,  2,  3,  4,  7,  8,  9, 10], dtype=int64), array([2, 2, 2, 2, 1, 1, 1, 1, 1], dtype=int64))


***6. Resize***

In [85]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(3,2))

print(y)

[[1 2]
 [3 4]
 [5 6]]


***7. Flatten***

In [86]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(3,2))

print(y)
print()

print(y.flatten())
print("Flatten : ",y.flatten(order = "F"))

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]
Flatten :  [1 3 5 2 4 6]


***8. Ravel***

In [87]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(3,2))

print(y)
print()

print(y.flatten())
print("Flatten : ",y.flatten(order = "F"))
print()
print("Ravel : ",np.ravel(y))
print("Ravel : ",np.ravel(y,order = "F")) #{'C','F','A','K'}

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]
Flatten :  [1 3 5 2 4 6]

Ravel :  [1 2 3 4 5 6]
Ravel :  [1 3 5 2 4 6]


***9. Insert***

In [88]:
import numpy as np

var = np.array([1,2,3,4])

print(var)
print(type(var))

v = np.insert(var, 2,40)
u = np.insert(var, (2,4),40)

print(v)
print(u)

[1 2 3 4]
<class 'numpy.ndarray'>
[ 1  2 40  3  4]
[ 1  2 40  3  4 40]


In [89]:
var1 = np.array([[1,2,3],[1,2,3]])

v1 = np.insert(var1 ,2 , 6, axis = 0)
v2 = np.insert(var1 ,2 , 6, axis = 1)
v3 = np.insert(var1 ,2 ,[22,23],axis = 1)

print(v1)
print()
print(v2)
print()
print(v3)

[[1 2 3]
 [1 2 3]
 [6 6 6]]

[[1 2 6 3]
 [1 2 6 3]]

[[ 1  2 22  3]
 [ 1  2 23  3]]


***10. Append***

In [90]:
var = np.array([1,2,3,4])

print(var)

x = np.append(var,6.5)
print(x)

[1 2 3 4]
[1.  2.  3.  4.  6.5]


In [91]:
var1 = np.array([[1,2,3],[1,2,3]])

v1 = np.append(var1,[[45,34,78]],axis = 0)
print(v1)

[[ 1  2  3]
 [ 1  2  3]
 [45 34 78]]


***11. Delete***

In [92]:
var = np.array([1,2,3,4])

print(var)
print()
d = np.delete(var,2)
print(d)

[1 2 3 4]

[1 2 4]


# Matrix in NumPy Arrays

***Matrix***

In [93]:
import numpy as np

var = np.matrix([[1,2,3],[1,2,3]])

print(var)
print(type(var))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [94]:
import numpy as np

var = np.matrix([[1,2,3],[1,2,3]])
var1 = np.matrix([[1,2,3],[1,2,3]])

print(var)
print()
print(type(var))
print()
print(var + var1)

[[1 2 3]
 [1 2 3]]

<class 'numpy.matrix'>

[[2 4 6]
 [2 4 6]]


***Array***

In [95]:
var1 = np.array([[1,2,3],[1,2,3]])

print(var1)
print(type(var1))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [96]:
var1 = np.array([[1,2,3],[1,2,3]])
var2 = np.array([[1,2,3],[1,2,3]])

print(var1)
print()
print(var2)
print()
print(type(var1))
print()
print(var1+var2)

[[1 2 3]
 [1 2 3]]

[[1 2 3]
 [1 2 3]]

<class 'numpy.ndarray'>

[[2 4 6]
 [2 4 6]]


# Arithmetic Operation in Matrix

In [97]:
import numpy as np

var = np.matrix([[1,2],[1,2]])
var2 = np.matrix([[1,2],[1,2]])

print(var)
print()
print(type(var))
print()
print(var2)
print()
print(type(var2))
print()
print(var*var2)
print()
print(var.dot(var2))

[[1 2]
 [1 2]]

<class 'numpy.matrix'>

[[1 2]
 [1 2]]

<class 'numpy.matrix'>

[[3 6]
 [3 6]]

[[3 6]
 [3 6]]


In [98]:
var1 = np.array([[1,2,3],[1,2,3]])

print(var1)
print(type(var1))
print()
print(var1*var1)

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>

[[1 4 9]
 [1 4 9]]


# Matrix Functions in NumPy Arrays

1. Transpose
2. Swapaxes
3. Inverse
4. Power
5. Determinate

***1. Transpose***

In [99]:
import numpy as np

var = np.matrix([[1,2,3],[4,5,6]])

print(var)
print()

print(np.transpose(var))
print()
print(var.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


***2. Swapaxes***

In [100]:
var2 = np.matrix([[1,2],[3,4]])

print(var2)
print()
print(np.swapaxes(var2,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


***3. Inverse***

In [101]:
var3 = np.matrix([[1,2],[3,4]])

print(var3)
print()

print(np.linalg.inv(var3))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


***4. Power***

In [102]:
var4 = np.matrix([[1,2],[3,4]])

print(var4)
print()

print(np.linalg.matrix_power(var4,2))
print()

print(np.linalg.matrix_power(var4,0))
print()

print(np.linalg.matrix_power(var4,-2))

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


***5. Determinate***

In [103]:
var5 = np.matrix([[1,2],[3,4]])

print(var5)
print()
print(np.linalg.det(var5))

[[1 2]
 [3 4]]

-2.0000000000000004


In [104]:
var5 = np.matrix([[1,2,3],[3,4,3],[1,2,3]])

print(var5)
print()
print(np.linalg.det(var5))

[[1 2 3]
 [3 4 3]
 [1 2 3]]

0.0
